name: system_date_time_format_hook_example
description: "Demonstrates how to use the system_date_time_format_hook plugin."
publish_to: 'none'

environment:
  sdk: ^3.2.0

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.3
  system_date_time_format_hook:
    path: ../

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
