name: system_date_time_format_hook
description: A flutter hook for system_date_time_format plugin for getting date and time format patterns from device system settings.
version: 1.3.0
repository: https://github.com/Nikoro/system_date_time_format_hook
issue_tracker: https://github.com/Nikoro/system_date_time_format_hook/issues

environment:
  sdk: ^3.2.0
  flutter: '>=3.16.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.3
  system_date_time_format: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mocktail: ^1.0.4
